### ISSUE TITLE
Error : No newoffset provided for prediction, yet offset used in fit of glmnet

### ISSUE THREAD

**Issue by blind-contours** [jeremyrcoyle/sl3#369]
Offset parameter for glmnet is called newoffset and so this algorithm errors out in the SL. I think this should be an easy fix so glmnet in SL3 can accept an offset.

**Comment by rachaelvp** [comment]
Hi @blind-contours I just made a PR with this fix [here](https://github.com/tlverse/sl3/pull/371). I haven't added a test yet for this, but I would like to. Do you happen to have a reproducible example with offset specified? If so, I can use this for the test for `Lrnr_glmnet`.
