### ISSUE TITLE
R 4.0 dependency (stringsAsFactors)

### ISSUE THREAD

**Issue by MichaelChirico** [jeremyrcoyle/sl3#375]
The stated R dependency is quite old:

https://github.com/tlverse/sl3/blob/2bc71d8e422da29c86f5e4327fe508c155c84735/DESCRIPTION#L32

But this code relies on the default behavior of `as.data.frame()`'s `stringsAsFactors = FALSE` in R 4.0 and later:

https://github.com/tlverse/sl3/blob/2bc71d8e422da29c86f5e4327fe508c155c84735/R/sl3_Task.R#L177

**Comment by nhejazi** [comment]
Thanks for bringing this up, it's a good find. I wasn't aware of changes to `as.data.frame()`'s default behavior, but it looks like `as.data.table()` has a `stringsAsFactors` argument that defaults to `FALSE`, and the `data.table` package is backwards compatible with R 3.1.0+, so I think it will suffice to update the minimum R version of `sl3` to match with that used by `data.table` (although in practice other dependencies will determine the limit) and to switch out that particular use of `as.data.frame()` with `as.data.table()`. I'll do that in a PR shortly.

**Comment by MichaelChirico** [comment]
yep, that'll work. thanks!

**Comment by nhejazi** [comment]
resolved by #378
