### ISSUE TITLE
Predicting from `Lrnr_sl`

### ISSUE THREAD

**Issue by emmavestesson** [jeremyrcoyle/sl3#399]
Hi,

I have trained a model with a binary outcome following the steps in chapter 6 of the tlverse handbook. When running the prediction step `sl_preds <- sl_fit$predict(task = task) ` (https://tlverse.org/tlverse-handbook/sl3.html#super-learner-and-candidate-learner-predictions) I think that is returning the predicted value but I would like to get the predicted probability, equivalent to `predict(type='response')`. Is there a way to do this? I've included an example below using the washb data.  

The reason I want to do this is that I want to check the propensity scores before running `tmle3()` (probably using pretrained models for the treatment mechanism). If there is a way of getting the propensity scores directly from running `tmle3()` then that would also work. 

``` r
library(data.table)
library(sl3)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:data.table':
#> 
#>     between, first, last
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union


washb_data <- fread(
  paste0(
    "https://raw.githubusercontent.com/tlverse/tlverse-data/master/",
    "wash-benefits/washb_data.csv"
  ),
  stringsAsFactors = TRUE
)

washb_data <- washb_data %>% 
  mutate(tr_binary = tr=='Control' )

task <- make_sl3_Task(
  data = washb_data,
  outcome = "tr_binary",
  covariates = c("tr", "fracode", "month", "aged", "sex", "momage", "momedu", 
                 "momheight", "hfiacat", "Nlt18", "Ncomp", "watmin", "elec", 
                 "floor", "walls", "roof", "asset_wardrobe", "asset_table", 
                 "asset_chair", "asset_khat", "asset_chouki", "asset_tv", 
                 "asset_refrig", "asset_bike", "asset_moto", "asset_sewmach", 
                 "asset_mobile")
)
#> Warning in process_data(data, nodes, column_names = column_names, flag = flag, :
#> Missing covariate data detected: imputing covariates.

lrn_glm <- Lrnr_glm$new()
lrn_mean <- Lrnr_mean$new()


stack <- Stack$new(
  lrn_glm, lrn_mean
)
    
sl <- Lrnr_sl$new(learners = stack, metalearner = Lrnr_nnls$new()) 

sl_fit <- sl$train(task = task)

sl_preds <- sl_fit$predict(task = task, type = "response")
#> Error in sl_fit$predict(task = task, type = "response"): unused argument (type = "response")
```

<sup>Created on 2022-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rachaelvp** [comment]
Hi @emmavestesson, thanks for bringing this up. The argument `type` is not an accepted argument for `predict` in sl3. This is why your call, `sl_fit$predict(task=task, type=“response”)`, is producing an error. The handbook example uses `sl_fit$predict(task=task)`. This is the correct formatting. What do the predictions look like when you run `sl_fit$predict(task=task)` (i.e., when you do not run the code that errors)? Could you please include, say, the first 10 predictions that are output by that call?

You can also obtain the estimated propensity scores from the tmle3 fit object. I will show you how to do that too when I to my laptop. It would be helpful in the meantime if you could please share those first few predictions so I can make sure the format of the binary outcome predictions is a predicted probability.

**Comment by emmavestesson** [comment]
Hi @rachaelvp, 

Thanks for replying so quickly, I really appreciate it. I can't share the actual values but they are all between 0-1 (not including 0 and 1). It would be great if you could share how to get the estimated propensity score from the tmle3 fit object when you have the opportunity. Thanks again for your help!

**Comment by rachaelvp** [comment]
Assuming your tmle3 fit object is named `tmle3_fit`, this is one way to extract the estimated propensity score from that object:
`propensity_score <- tmle3_fit$likelihood$initial_likelihood$factor_list$A$learner$predict()`
