### ISSUE TITLE
Lrnr_glmnet bug

### ISSUE THREAD

**Issue by benkeser** [jeremyrcoyle/sl3#409]
https://github.com/tlverse/sl3/blob/6544257626080f96fb37595a8a1f77a7c80918d1/R/Lrnr_glmnet.R#L105

This logic fails if new learner is defined as

```r
sl3::Lrnr_glmnet$new(family = stats::binomial())
```

due to the fact that `stats::binomial()` returns object of class `family` which has length > 1.

On the other hand, it appears that learners like `Lrnr_glm` may expect objects of class `family`, e.g.,

https://github.com/tlverse/sl3/blob/6544257626080f96fb37595a8a1f77a7c80918d1/R/Lrnr_glm.R#L64-L66

So it seems like there are some logical inconsistencies in terms of what the expected input is for `family`.

**Comment by rachaelvp** [comment]
Thanks for pointing this out! The logic that's causing your error is removed in this [PR](https://github.com/tlverse/sl3/pull/410). About to merge this into the devel branch of sl3. 

The `"glm"` class object that's returned by a call to `glm` is not included in the `Lrnr_glm` fit objects, as it is apparently very large. I am not entirely sure, but I believe the family object's link function is broken down for a similar reason.
