### ISSUE TITLE
SL Parallel processing for large dataset question

### ISSUE THREAD

**Issue by joecosmosx** [jeremyrcoyle/sl3#429]
Hello tlverse team,

I have a question about utilizing the parallel processing feature.  I just naively tested the super learning with parallel processing with the data from one of your examples, and just scale up that by 5000 times, and I compared the running time with the sequential processing, but the results suggested parallel processing takes more time. Please see the picture below, the first column means by how much I scaled up data, for example, if I have 100 rows in the original data, then 5000 means I duplicate the data and append to it 5000 times, the processing column means if it is parallel(par) or sequential(seq).  I tested it on a server that has 48 cores and 96 virtual processors with about 760 GB RAM.

Do you have any suggestion to fully utilize the parallel processing for a very large dataset? 
Thank you for your time!

Best,
Joe 

<img width="380" alt="Screenshot 2024-01-09 154830" src="https://github.com/tlverse/sl3/assets/10256179/7ac8b5db-26de-403d-adc9-1936fffd1756">

Code for reference:

```{r}
report<-data.frame(matrix(0,nrow = 4, ncol = 5 ))
colnames(report)<-c('data_mult','processing','system time','elapsed time','size(MB)')
report[,1] <- rep(c(500,5000),2)
report[,2] <- rep(c('seq','par'),each = 2)
```

```{r}
set.seed(49753)
library(tidyverse)
library(data.table)
library(SuperLearner)
library(origami)
library(future)
library(sl3)

# load example data set
data(cpp)
cpp <- cpp %>%
  dplyr::filter(!is.na(haz)) %>%
  mutate_all(~ replace(., is.na(.), 0))

# use covariates of intest and the outcome to build a task object
covars <- c("apgar1", "apgar5", "parity", "gagebrth", "mage", "meducyrs",
            "sexn")
n_times <- 5000 #500
# Duplicate the DataFrame n times
duplicates <- replicate(n_times, cpp, simplify = FALSE)

# Concatenate the duplicates together
merged_df <- do.call(rbind, duplicates)

task <- sl3_Task$new(
  data = merged_df,
  covariates = covars,
  outcome = "haz"
)

size = object.size(merged_df)/(1024^2)

# set up screeners and learners via built-in functions and pipelines
slscreener <- Lrnr_pkg_SuperLearner_screener$new("screen.glmnet")
glm_learner <- Lrnr_glm$new()
xgb_learner <- Lrnr_xgboost$new()
nnet_learner <- Lrnr_nnet$new()
screen_and_glm <- Pipeline$new(slscreener, glm_learner)
screen_and_xgb <- Pipeline$new(slscreener, xgb_learner)
screen_and_nnet <- Pipeline$new(slscreener, nnet_learner)
SL.glmnet_learner <- Lrnr_pkg_SuperLearner$new(SL_wrapper = "SL.glmnet")

# stack learners into a model (including screeners and pipelines)
learner_stack <- Stack$new(SL.glmnet_learner, glm_learner, screen_and_xgb,screen_and_nnet, screen_and_glm)
start_time <- proc.time()
stack_fit <- learner_stack$train(task)
stime = proc.time() - start_time
print(stime)
if (n_times == 500) {
  report[1,3]<- stime[2]
  report[1,4]<- stime[3]
  report[1,5]<- size
  
  
}else{
  report[2,3]<- stime[2]
  report[2,4]<- stime[3]
  report[2,5]<- size
}
# preds <- stack_fit$predict()
```
```{r}
ncores <- availableCores()-1
plan(multicore, workers = ncores )
start_time <- proc.time()
# now, let's re-train our Stack in parallel
stack_fit <- learner_stack$train(task)
ptime = proc.time() - start_time
print(ptime)

if (n_times == 500) {
  report[3,3]<- ptime[2]
  report[3,4]<- ptime[3]
  report[3,5]<- size
  
  
}else{
  report[4,3]<- ptime[2]
  report[4,4]<- ptime[3]
  report[4,5]<- size
}

```

**Comment by jeremyrcoyle** [comment]
Are you running this in an interactive R session or via the command line as in `R < script.R` ?

**Comment by joecosmosx** [comment]
I ran them in the R studio

**Comment by joecosmosx** [comment]
> Are you running this in an interactive R session or via the command line as in `R < script.R` ?

I ran them in the R studio. Is that the reason? Do I need to run it via the command line?
Just to add that CPU utilization was very low during parallel processing

An update: I tried running it via the command line, but it did not seem to use more cores, and a 70 MB data and a binary prediction task with 8 CV folds took about 12 hours to run.

**Comment by joecosmosx** [comment]
Need to use multisession in Windows, and it is working. But the utilization seems limited. When I register more cores, not all were used.
